# Generated by Django 5.2.3 on 2025-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCarsWash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(max_length=100),
        ),
    ]
