# Generated by Django 5.2.3 on 2025-06-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCarsWash', '0002_alter_cita_duracion_alter_cita_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APPCarsWash.vehiculo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
