# Generated by Django 5.2.3 on 2025-06-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPCarsWash', '0003_cita_vehiculo_alter_cita_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rut',
        ),
    ]
